### PR TITLE
Upgrading PHP and PHPMyAdmin

### PR DESCRIPTION
**Pull request by mikekasprzak**

### CODE REVIEW

**Comment by zwrawr** [comment]
```
default: Reading package lists...
    default: Reading package lists...
    default: Building dependency tree...
    default: 
    default: Reading state information...
    default: E: Unable to locate package php7.1
    default: E: Couldn't find any package by glob 'php7.1'
    default: E: Couldn't find any package by regex 'php7.1'
    default: E: Unable to locate package php7.1-dev
    default: E: Couldn't find any package by glob 'php7.1-dev'
    default: E: Couldn't find any package by regex 'php7.1-dev'
    default: E: Unable to locate package php7.1-mbstring
    default: E: Couldn't find any package by glob 'php7.1-mbstring'
    default: E: 
    default: Couldn't find any package by regex 'php7.1-mbstring'
    default: E: Unable to locate package php7.1-mysql
    default: E: Couldn't find any package by glob 'php7.1-mysql'
    default: E: Couldn't find any package by regex 'php7.1-mysql'
    default: E: Unable to locate package php7.1-xml
    default: E: Couldn't find any package by glob 'php7.1-xml'
    default: E: Couldn't find any package by regex 'php7.1-xml'
    default: E: Unable to locate package php7.1-opcache
    default: E: Couldn't find any package by glob 'php7.1-opcache'
    default: E: Couldn't find any package by regex 'php7.1-opcache'
    default: E: Unable to locate package php7.1-gd
    default: E: Couldn't find any package by glob 'php7.1-gd'
    default: E: Couldn't find any package by regex 'php7.1-gd'
    default: E: Unable to locate package php7.1-curl
    default: E: Couldn't find any package by glob 'php7.1-curl'
    default: E: Couldn't find any package by regex 'php7.1-curl'
    default: E: Unable to locate package php7.1-zip
    default: E: Couldn't find any package by glob 'php7.1-zip'
    default: E: Couldn't find any package by regex 'php7.1-zip
```
ubuntu 16 doesn't have php7.1 you'll need to re add that ppa

```
vagrant@dairybox:~$ sudo apt-cache search php7
libapache2-mod-php7.0 - server-side, HTML-embedded scripting language (Apache 2 module)
php-all-dev - package depending on all supported PHP development packages
php7.0 - server-side, HTML-embedded scripting language (metapackage)
php7.0-cgi - server-side, HTML-embedded scripting language (CGI binary)
php7.0-cli - command-line interpreter for the PHP scripting language
php7.0-common - documentation, examples and common module for PHP
php7.0-curl - CURL module for PHP
php7.0-dev - Files for PHP7.0 module development
php7.0-gd - GD module for PHP
php7.0-gmp - GMP module for PHP
php7.0-json - JSON module for PHP
php7.0-ldap - LDAP module for PHP
php7.0-mysql - MySQL module for PHP
php7.0-odbc - ODBC module for PHP
php7.0-opcache - Zend OpCache module for PHP
php7.0-pgsql - PostgreSQL module for PHP
php7.0-pspell - pspell module for PHP
php7.0-readline - readline module for PHP
php7.0-recode - recode module for PHP
php7.0-snmp - SNMP module for PHP
php7.0-sqlite3 - SQLite3 module for PHP
php7.0-tidy - tidy module for PHP
php7.0-xml - DOM, SimpleXML, WDDX, XML, and XSL module for PHP
php7.0-xmlrpc - XMLRPC-EPI module for PHP
libphp7.0-embed - HTML-embedded scripting language (Embedded SAPI library)
php7.0-bcmath - Bcmath module for PHP
php7.0-bz2 - bzip2 module for PHP
php7.0-enchant - Enchant module for PHP
php7.0-fpm - server-side, HTML-embedded scripting language (FPM-CGI binary)
php7.0-imap - IMAP module for PHP
php7.0-interbase - Interbase module for PHP
php7.0-intl - Internationalisation module for PHP
php7.0-mbstring - MBSTRING module for PHP
php7.0-mcrypt - libmcrypt module for PHP
php7.0-phpdbg - server-side, HTML-embedded scripting language (PHPDBG binary)
php7.0-soap - SOAP module for PHP
php7.0-sybase - Sybase module for PHP
php7.0-xsl - XSL module for PHP (dummy)
php7.0-zip - Zip module for PHP
php7.0-dba - DBA module for PHP
vagrant@dairybox:~$ 

```

**Comment by zwrawr** [comment]
The site may still work because php7.0 is already installed

**Comment by mikekasprzak** [comment]
Aren't we using the ppa?

**Comment by mikekasprzak** [comment]
Ah I see, you disabled the PPA. Okay, I'm doing a test run with it re-enabled (doing it by hand inside the VM worked fine), and will push once confirmed.

**Comment by zwrawr** [comment]
php7.1 breaks at least a few things

**Comment by zwrawr** [comment]
and fyi, i disabled the ppa because php7.0 is EOL and no longer in that repo

**Comment by mikekasprzak** [comment]
Got any examples of what it breaks? From my test it ran fine (or rather ran the same).

**Comment by mikekasprzak** [comment]
Oh I see, redis died. Okay. Might require 7.2 then, but yeah in the mean time there's 7.0 like you said.

**Pull request merged**
